services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot
      - ./uploads:/app/uploads:ro
    depends_on: [backend, frontend]
    restart: always

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    volumes:
      - ./config/application.properties:/config/application.properties:ro
      - ./uploads:/app/uploads
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - SPRING_CONFIG_LOCATION=file:/config/application.properties
      - SPRING_PROFILES_ACTIVE=prod

      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=5MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=20MB
      - TZ=America/New_York
    restart: always

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: redis
    volumes:
      - redis_data:/data
    restart: always

  mongodb:
    image: mongo:6
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    restart: always
    ports:
      - "27017:27017"

  jenkins:
    build: ./jenkins
    container_name: jenkins
    user: root
    ports:
      - "8081:8080"
    environment:
      - TZ=Asia/Seoul
      - JAVA_OPTS=-Duser.timezone=Asia/Seoul
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/srv/ur
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

volumes:
  jenkins_home:
  mysql_data:
  redis_data:
  mongo_data:
  portainer_data:
